services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: changemeinprod!
    ports:
      - "5432:5432"
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080
    depends_on:
      - db